### Basic ANN Program

In [13]:
import torch

In [2]:
import torch.nn as nn

In [3]:
class SimpleNN(nn.Module):
    def __init__(self,input_size,hidden_size,output_size) :
        super().__init__()
        self.l1=nn.Linear(input_size,hidden_size)
        self.relu=nn.ReLU()
        self.l2=nn.Linear(hidden_size,output_size)

    def forward(self,x):
        x=self.l1(x)
        x= self.relu(x)
        x=self.l2(x)
        return x

In [10]:
model=SimpleNN(input_size=4,hidden_size=5,output_size=3)

In [11]:
x=torch.tensor([[1.0,2.2,4.4,3.3]])
output=model(x)

In [12]:
output

tensor([[-0.1514,  0.3434,  0.2794]], grad_fn=<AddmmBackward0>)

### Beginner ANN Program

In [8]:
import torch
import torch.nn as nn

In [27]:
class myfirst(nn.Module):
    def __init__(self,input_size,output_size,hidden_size):
        super().__init__()
        self.layer1=nn.Linear(input_size,hidden_size)
        self.relu=nn.ReLU()
        self.output_laye=nn.Linear(hidden_size,output_size)

    def forward(self,input):
        
        input=self.layer1(input)
        input=self.relu(input)
        input=self.output_laye(input)
        return input

In [28]:
firstmodel = myfirst(input_size=2,output_size=1,hidden_size=1)

In [29]:
input=torch.tensor([[4.2,5.4]])
opt =firstmodel(input)

In [30]:
opt

tensor([[0.0003]], grad_fn=<AddmmBackward0>)

### 2nd Program to 

In [32]:
import torch
import torch.nn as nn

In [39]:
class Myclass(nn.Module):
    def __init__(self,inputs,hidden_nuron,outputs):
        super().__init__()
        self.layer1_fc= nn.Linear(inputs,hidden_nuron)
        self.relu=nn.ReLU()
        self.output_layer=nn.Linear(hidden_nuron,outputs)
        # self.relu2=nn.ReLU()

    def forward(self,input):
        input=self.layer1_fc(input)
        input=self.relu(input)
        input=self.output_layer(input)
        return(input)

In [42]:
model=Myclass(inputs=4,hidden_nuron=5,outputs=2)


In [46]:
input2 = torch.tensor([[1.0,2.0,3.0,4.0]])
opt = model(input2)
opt


tensor([[ 0.0724, -2.2343]], grad_fn=<AddmmBackward0>)

### AND GATE Model Building

In [63]:
import torch
import torch.nn as nn

In [64]:
class ANDAGATE(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer_fc=nn.Linear(2,1)
    def forward(self,x):
        x=self.layer_fc(x)
        x=torch.sigmoid(x)
        return x

In [65]:
model = ANDAGATE()

In [66]:
x = torch.tensor([[0.,0.],[0.,1.],[1.0,0.0],[1.0,1.0]])
y = torch.tensor([[0.],[0.],[0.],[1.]])

In [67]:
loss_counter = nn.BCELoss()


In [68]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.1)

In [84]:
for epoch in range(400):

    optimizer.zero_grad() #reset old gradient

    output=model(x)  #forward pass

    loss = loss_counter(output,y) # compute loss

    loss.backward()  # backward Propagation

    optimizer.step() # update Weights

    if epoch % 200 == 0:
        print(epoch, loss.item())

0 0.010617327876389027
200 0.010488144122064114


In [85]:
print(model(x))

tensor([[2.5874e-06],
        [1.2103e-02],
        [1.2103e-02],
        [9.8305e-01]], grad_fn=<SigmoidBackward0>)


In [90]:
x.shape[0]


4

### OR Gate Model In ANN

In [161]:
import torch
import  torch.nn as nn

In [162]:
a = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
b = torch.tensor([[0.],[1.],[1.],[1.]])

In [163]:
class ORGATE(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1= nn.Linear(2,1)

    def forward(self,a):
        a= self.layer1(a)
        a = torch.sigmoid(a)
        return a

model2 = ORGATE() 


In [164]:
loss_count = nn.BCELoss()

In [170]:
optimizer2 = torch.optim.SGD(model.parameters(),lr=0.5)

In [173]:
for epoch in range(2000):

    optimizer2.zero_grad()
    outputs2 = model2(a)
    loss = loss_count(outputs2,b)
    loss.backward()
    optimizer2.step()

    if(epoch % 200 == 0):
      print(epoch, loss.item())

0 0.7546882033348083
200 0.7546882033348083
400 0.7546882033348083
600 0.7546882033348083
800 0.7546882033348083
1000 0.7546882033348083
1200 0.7546882033348083
1400 0.7546882033348083
1600 0.7546882033348083
1800 0.7546882033348083


In [172]:
print(model2(a))

tensor([[0.4882],
        [0.3745],
        [0.5662],
        [0.4503]], grad_fn=<SigmoidBackward0>)


### NAND GATE WITH ANN 


In [1]:
import torch
import torch.nn as nn

In [2]:
class NANDGATE(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(2,1)

    def forward(self,x):
        x=self.layer1(x)
        x=torch.sigmoid(x)
        return(x)

In [5]:
nandmodel= NANDGATE()

In [6]:
x=torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y=torch.tensor([[1.],[1.],[1.],[0.]])

In [11]:
loss_count2=nn.BCELoss()

In [12]:
optimizer=torch.optim.SGD(nandmodel.parameters(),lr=0.4)

In [16]:
for epoch in range(1000):
    
    optimizer.zero_grad()
    outputs3 = nandmodel(x)
    loss = loss_count2(outputs3,y)
    loss.backward()
    optimizer.step()

    if epoch % 200 == 0:
        print(epoch,loss.item())

0 0.03590776398777962
200 0.03090222179889679
400 0.02710425853729248
600 0.024126894772052765
800 0.021731846034526825


In [17]:
print(nandmodel(x))

tensor([[1.0000],
        [0.9771],
        [0.9771],
        [0.0321]], grad_fn=<SigmoidBackward0>)


### XOR GATE WITH ANN 

In [39]:
import torch
import torch.nn as nn

In [40]:
c = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])

d = torch.tensor([[0.],[1.],[1.],[0.]])

In [41]:
print(f"Shape Of C : {c.shape}")
print(f"Shape of D :{d.shape}")

Shape Of C : torch.Size([4, 2])
Shape of D :torch.Size([4, 1])


In [42]:
class XORGATE(nn.Module):
    def __init__(self,input_size,output_size,hiddenlayer_nueron):
        super().__init__()
        self.hidden_layer = nn.Linear(input_size,hiddenlayer_nueron)
        self.output_layer = nn.Linear(hiddenlayer_nueron, output_size)

    def forward(self,c):
        activation_fn = torch.sigmoid(self.hidden_layer(c))

        c = torch.sigmoid(self.output_layer(activation_fn))
        return c

XORModel = XORGATE(input_size=2,output_size=1,hiddenlayer_nueron=2)

In [43]:
loss_count3 = nn.BCELoss()

In [44]:
optimizer3 = torch.optim.SGD(XORModel.parameters(),lr=0.5)

In [72]:
for epoch in range(22000):
    optimizer3.zero_grad()

    outputs4 = XORModel(c)

    loss = loss_count3(outputs4,d)

    loss.backward()

    optimizer3.step()

    if epoch % 1000 == 0 :
        print(epoch,loss.item())

0 0.0009193535661324859
1000 0.0008955560624599457
2000 0.0008729092660360038
3000 0.0008513727225363255
4000 0.000830930017400533
5000 0.0008113861549645662
6000 0.0007927894475869834
7000 0.0007749645737931132
8000 0.0007578994845971465
9000 0.0007416262524202466
10000 0.0007260726997628808
11000 0.0007110588485375047
12000 0.0006967322551645339
13000 0.0006829582271166146
14000 0.0006696855998598039
15000 0.0006569355609826744
16000 0.0006446243496611714
17000 0.0006328088929876685
18000 0.0006214185850694776
19000 0.0006104292115196586
20000 0.0005997961852699518
21000 0.0005895467475056648


In [73]:
print(XORModel(c))


tensor([[6.7085e-04],
        [9.9952e-01],
        [9.9952e-01],
        [6.8369e-04]], grad_fn=<SigmoidBackward0>)


### NOR GATE WITH ANN

In [53]:
import torch
import torch.nn

In [55]:
input_x = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
output_y = torch.tensor([[1.],[0.],[0.],[0.]])

In [56]:
class NORGATE(nn.Module):
    def __init__(self):
        super().__init__()
        self.input_layer  = nn.Linear(2,2)
        self.output_layer = nn.Linear(2,1)

    def forward(self,input_x):
        activation_fn = torch.sigmoid(self.input_layer(input_x))
        input_x = torch.sigmoid(self.output_layer(activation_fn))
        return input_x

In [57]:
NORModel = NORGATE()

In [59]:
loss_count4 = nn.BCELoss()

In [67]:
optimizer4 = torch.optim.SGD(NORModel.parameters(),lr=0.5)

In [74]:
for epoch in range(20000):
   optimizer4.zero_grad()
   outputs5 = NORModel(input_x)
   loss = loss_count4(outputs5, output_y)
   loss.backward()
   optimizer4.step()

   if epoch % 100 == 0 :
        print(epoch,loss.item())

0 0.0002840407832991332
100 0.00028283396386541426
200 0.0002816548221744597
300 0.00028047594241797924
400 0.00027929904172196984
500 0.00027816399233415723
600 0.0002770209976006299
700 0.0002758940972853452
800 0.00027476102695800364
900 0.0002736333990469575
1000 0.00027251167921349406
1100 0.0002714261645451188
1200 0.0002703430945985019
1300 0.00026923613040708005
1400 0.000268154835794121
1500 0.00026710343081504107
1600 0.00026603194419294596
1700 0.000264995323959738
1800 0.00026396120665594935
1900 0.00026289880042895675
2000 0.0002618675061967224
2100 0.00026088079903274775
2200 0.00025985794491134584
2300 0.00025886663934215903
2400 0.00025787550839595497
2500 0.0002568894997239113
2600 0.00025590628501959145
2700 0.0002549284545239061
2800 0.0002539483830332756
2900 0.000253000995144248
3000 0.00025205782731063664
3100 0.0002510859339963645
3200 0.0002501450071576983
3300 0.0002492082421667874
3400 0.0002483129210304469
3500 0.00024738474166952074
3600 0.000246482697548344

In [75]:
print(NORModel(input_x))

tensor([[9.9961e-01],
        [9.8583e-05],
        [9.7907e-05],
        [2.2336e-05]], grad_fn=<SigmoidBackward0>)
